name: CI with Docker + Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t tf-test .

      - name: Run Terraform inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app tf-test bash -c "
            cd /app && \
            terraform init && \
            terraform apply -auto-approve
          "
